services:
  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: www
      POSTGRES_PASSWORD: www
      POSTGRES_DB: www_test
    ports:
      - "5434:5432"
    volumes:
      - www_pg_test:/var/lib/postgresql/data

volumes:
  www_pg_test:
