services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: www
      POSTGRES_PASSWORD: www
      POSTGRES_DB: www
    ports:
      - "5432:5432"
    volumes:
      - www_pg:/var/lib/postgresql/data

volumes:
  www_pg:
